name: flutter image build and push

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'flutter version'
        required: true
        default: 'stable'


jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: login to github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup image version'
        run: |
          if [ ${{ github.event.inputs.flutter_version == 'stable '}} ]; then
            echo "image_tag=latest" >> $GITHUB_ENV
          else
            echo "image_tag=${{ github.event.inputs.flutter_version }}" >> $GITHUB_ENV
          fi


      - name: build and push image
        env:
          IMAGE_VERSION: ${{ github.event.inputs.flutter_version == 'stable '}}
        id: flutter_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/flutter:${{ env.image_tag }}
          build-args: |
            flutter_version=${{ github.event.inputs.flutter_version }}
